{
  "openapi": "3.0.1",
  "info": {
    "title": "Network API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local"
    },
    {
      "url": "https://developmentapi.ienterprise.info/network",
      "description": "Dev"
    },
    {
      "url": "https://stagingapi.ienterprise.com/network",
      "description": "Staging"
    }
  ],
  "paths": {
    "/network/devices/clients/{storeNumber}": {
      "get": {
        "tags": [
          "network-api"
        ],
        "summary": "Returns network data(network details, devices and clients) by store number",
        "operationId": "getNetworks",
        "parameters": [
          {
            "name": "storeNumber",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseNetworkData"
                }
              }
            }
          },
          "401": {
            "description": "Returns unauthorized/forbidden response code"
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "messageCodes": [
                    "unknown.error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/network/devices/clients/{storeNumber}/filter/mobiledevices/{serialNumber}": {
      "get": {
        "tags": [
          "network-api"
        ],
        "summary": "Returns network data(network details, devices and clients) by store number",
        "operationId": "getNetworksFilterMobileDevices",
        "parameters": [
          {
            "name": "storeNumber",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "serialNumber",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseNetworkData"
                }
              }
            }
          },
          "401": {
            "description": "Returns unauthorized/forbidden response code"
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "messageCodes": [
                    "unknown.error"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponseNetworkData": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "$ref": "#/components/schemas/NetworkData"
          }
        }
      },
      "IndicatorInfo": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string",
            "enum": [
              "RED",
              "GREEN"
            ]
          },
          "reasonCodes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ReasonCode"
            }
          },
          "indicatorCodes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ReasonCode"
            }
          }
        }
      },
      "Network": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "timeZone": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "productTypes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "NetworkClient": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "mac": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "ip": {
            "type": "string"
          },
          "ip6": {
            "type": "string"
          },
          "user": {
            "type": "string"
          },
          "firstSeen": {
            "type": "string"
          },
          "lastSeen": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "os": {
            "type": "string"
          },
          "ssid": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "usage": {
            "type": "object",
            "additionalProperties": {
              "type": "integer",
              "format": "int64"
            }
          },
          "recentDeviceSerial": {
            "type": "string"
          },
          "recentDeviceName": {
            "type": "string"
          },
          "recentDeviceMac": {
            "type": "string"
          },
          "recentDeviceConnection": {
            "type": "string"
          },
          "deviceTypePrediction": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "IPHONE_OR_IPAD",
              "WATCH_TOWER",
              "UNKNOWN",
              "PRINTER"
            ]
          },
          "switchPort": {
            "type": "string"
          },
          "indicatorInfo": {
            "$ref": "#/components/schemas/IndicatorInfo"
          },
          "additionalData": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          }
        }
      },
      "NetworkData": {
        "type": "object",
        "properties": {
          "network": {
            "$ref": "#/components/schemas/Network"
          },
          "devices": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/NetworkDevice"
            }
          },
          "clients": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/NetworkClient"
            }
          }
        }
      },
      "NetworkDevice": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "serial": {
            "type": "string"
          },
          "mac": {
            "type": "string"
          },
          "networkId": {
            "type": "string"
          },
          "productType": {
            "type": "string"
          },
          "model": {
            "type": "string"
          },
          "wanIp": {
            "type": "string"
          },
          "firmware": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "publicIp": {
            "type": "string"
          },
          "lanIp": {
            "type": "string"
          },
          "ipType": {
            "type": "string"
          },
          "primaryDns": {
            "type": "string"
          },
          "secondaryDns": {
            "type": "string"
          },
          "gateway": {
            "type": "string"
          },
          "indicatorInfo": {
            "$ref": "#/components/schemas/IndicatorInfo"
          },
          "additionalData": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "SWITCH",
              "UNKNOWN",
              "ACCESS_POINT"
            ]
          }
        }
      },
      "ReasonCode": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  }
}
